#server.servlet.context-path: /cookie-app
server.port: 8081
spring.jpa.hibernate.ddl-auto: update
app.db.location: ${APP_DB_LOCATION:./db/doc}
spring.jpa.hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
spring.h2.console.settings.web-allow-others: true
spring.datasource.url: ${JDBC_DATABASE_URL}
spring.datasource.driverClassName: org.postgresql.Driver
spring.datasource.validationQuery: SELECT 1
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled: true
spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 100MB
cloudinary:
  cloudname: ${CLOUD_NAME}
  key: ${CLOUD_KEY}
  secret: ${CLOUD_SECRET}
